// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PingResponse struct {
	Message    string `json:"message"`
	ServerTime string `json:"serverTime"`
}

type Query struct {
}
