package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63 DO NOT EDIT.

import (
	"context"
	"log"

	"connectrpc.com/connect"
	"github.com/LuciKritZ/syzygium/apps/gateway/graph/model"

	// Import your generated protos
	pingv1 "github.com/LuciKritZ/syzygium/libs/protos/gen/go/infrastructure/v1"
)

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context, message string) (*model.PingResponse, error) {
	// 1. Create the gRPC Client (Connecting to template-go on port 8080)
	// In production, you would initialize this once in server.go and reuse it

	// 2. Call the Backend
	req := connect.NewRequest(&pingv1.PingRequest{
		Message: message,
	})

	log.Printf("Gateway received GraphQL request: %s", message)

	resp, err := r.Registry.PingClient.Ping(ctx, req)
	if err != nil {
		log.Printf("❌ Error calling backend: %v", err)
		return nil, err
	}

	// 3. Convert gRPC response to GraphQL Model
	return &model.PingResponse{
		Message:    resp.Msg.Message,
		ServerTime: resp.Msg.ServerTime,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
